export const SET_ERROR = 'SET_ERROR';

export const LOGOUT = 'LOGOUT';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';

export const RESET_PASSWORD = 'RESET_PASSWORD';
export const RESET_PASSWORD_START = 'RESET_PASSWORD_START';
export const RESET_PASSWORD_SUCCESS = 'RESET_PASSWORD_SUCCESS';
export const RESET_PASSWORD_FAILED = 'RESET_PASSWORD_FAILED';

export const SET_NEW_PASSWORD = 'SET_NEW_PASSWORD';
export const SET_NEW_PASSWORD_START = 'SET_NEW_PASSWORD_START';
export const SET_NEW_PASSWORD_SUCCESS = 'SET_NEW_PASSWORD_SUCCESS';
export const SET_NEW_PASSWORD_FAILED = 'SET_NEW_PASSWORD_FAILED';

export const FETCH_AUTH_USER = 'FETCH_AUTH_USER';
export const FETCH_AUTH_USER_SUCCESS = 'FETCH_AUTH_USER_SUCCESS';
export const FETCH_AUTH_USER_FAILED = 'FETCH_AUTH_USER_FAILED';

export const ADD_ALBUM_IDS = 'ADD_ALBUM_IDS';

export const LOGIN = 'LOGIN';
export const LOGIN_START = 'LOGIN_START';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILED = 'LOGIN_FAILED';

export const REGISTER = 'REGISTER';
export const REGISTER_START = 'REGISTER_START';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAILED = 'REGISTER_FAILED';

export const SAVE_PROFILE = 'SAVE_PROFILE';
export const SAVE_PROFILE_FAILED = 'SAVE_PROFILE_FAILED';

export const CREATE_ALBUM = 'CREATE_ALBUM';
export const CREATE_ALBUM_SUCCESS = 'CREATE_ALBUM_SUCCESS';

export const DELETE_ALBUM = 'DELETE_ALBUM';
export const DELETE_ALBUM_SUCCESS = 'DELETE_ALBUM_SUCCESS';
export const DELETE_IMAGES_BY_ALBUM_ID = 'DELETE_IMAGES_BY_ALBUM_ID';

export const EDIT_ALBUM = 'EDIT_ALBUM';
export const EDIT_ALBUM_SUCCESS = 'EDIT_ALBUM_SUCCESS';

export const FETCH_ALBUMS = 'FETCH_ALBUMS';
export const FETCH_ALBUMS_START = 'FETCH_ALBUMS_START';
export const FETCH_ALBUMS_SUCCESS = 'FETCH_ALBUMS_SUCCESS';
export const FETCH_ALBUMS_FAILED = 'FETCH_ALBUMS_FAILED';

export const FETCH_ALBUM_SUCCESS = 'FETCH_ALBUM_SUCCESS';

export const UPDATE_ALBUM_SUCCESS = 'UPDATE_ALBUM_SUCCESS';

export const INC_ALBUM_OFFSET = 'INC_ALBUM_OFFSET';
export const RESET_ALBUM_OFFSET = 'RESET_ALBUM_OFFSET';

export const GET_ALBUM = 'GET_ALBUM';
export const GET_ALBUM_SUCCESS = 'GET_ALBUM_SUCCESS';
export const GET_AUTH_ALBUM_SUCCESS = 'GET_AUTH_ALBUM_SUCCESS';
export const GET_AUTH_ALBUM_FAILED = 'GET_ALBUM_FAILED';

export const GET_USER_ALBUM_SUCCESS = 'GET_USER_ALBUM_SUCCESS';

export const FETCH_USER = 'FETCH_USER';
export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS';

export const FETCH_NEWS = 'FETCH_NEWS';
export const FETCH_NEWS_SUCCESS = 'FETCH_NEWS_SUCCESS';
export const ADD_NEWS = 'ADD_NEWS';
export const DELETE_NEWS = 'DELETE_NEWS';

export const FETCH_IMAGES_BY_ALBUM_ID = 'FETCH_IMAGES_BY_ALBUM_ID';
export const FETCH_IMAGES_START = 'FETCH_IMAGES_START';
export const FETCH_IMAGES_SUCCESS = 'FETCH_IMAGES_SUCCESS';
export const FETCH_IMAGE_SUCCESS = 'FETCH_IMAGE';
export const LOAD_IMAGES = 'LOAD_IMAGES';

export const UPDATE_IMAGE_SUCCESS = 'UPDATE_IMAGE_SUCCESS';

export const EDIT_IMAGE = 'EDIT_IMAGE';

export const GET_ACTIVE_IMAGE = 'EDIT_ACTIVE_IMAGE';

export const DELETE_IMAGE = 'DELETE_IMAGE';
export const DELETE_IMAGE_SUCCESS = 'DELETE_IMAGE_SUCCESS';

export const ADD_COMMENT = 'ADD_COMMENT';

export const LIKE_IMAGE = 'LIKE_IMAGE';

export const SET_SEARCH_QUERY = 'SET_SEARCH_QUERY';
export const FETCH_SEARCH_RESULTS = 'FETCH_SEARCH_RESULTS';
export const FETCH_SEARCH_RESULTS_START = 'FETCH_SEARCH_RESULTS_START';
export const FETCH_SEARCH_RESULTS_SUCCESS = 'FETCH_SEARCH_RESULTS_SUCCESS';

export const FIND_USER_ALBUM = 'FIND_USER_ALBUM';
export const RESET_USER_SEARCH = 'RESET_USER_SEARCH';